[package]
edition = "2021"
name    = "fig"
version = "0.3.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap        = { version = "4.1", features = ["derive"] }
directories = "5.0"
git2        = "0.16"
glob        = "0.3"
miette      = { version = "5.5", features = ["fancy"] }
owo-colors  = "3.5"
serde       = { version = "1.0", features = ["derive"] }
serde_json  = "1.0"
thiserror   = "1.0"
toml        = "0.7"
