[package]
edition = "2021"
name    = "fig"
version = "0.3.4"

[dependencies]
clap        = { version = "4.1", features = ["derive"] }
directories = { version = "5.0" }
git2        = { version = "0.17" }
glob        = { version = "0.3" }
log         = { version = "0.4", features = ["kv_unstable"] }
miette      = { version = "5.8", features = ["fancy"] }
owo-colors  = { version = "3.5" }
serde       = { version = "1.0", features = ["derive"] }
serde_json  = { version = "1.0" }
simplelog   = { version = "0.12" }
thiserror   = { version = "1.0" }
toml        = { version = "0.7" }