[package]
edition = "2021"
name    = "fig"
version = "1.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap        = { version = "4.0.15", features = ["derive"] }
directories = "4.0.1"
git2        = "0.15.0"
miette      = { version = "5.3.0", features = ["fancy"] }
serde       = { version = "1.0.145", features = ["derive"] }
thiserror   = "1.0.37"
toml        = "0.5.9"
