[package]
edition = "2021"
name    = "fig"
version = "0.3.3"

[dependencies]
clap        = { version = "4.1", features = ["derive"] }
directories = "5.0"
git2        = "0.16"
glob        = "0.3"
log         = { version = "0.4", features = ["kv_unstable"] }
miette      = { version = "5.5", features = ["fancy"] }
owo-colors  = "3.5"
serde       = { version = "1.0", features = ["derive"] }
serde_json  = "1.0"
simplelog   = "0.12"
thiserror   = "1.0"
toml        = "0.7"
